version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./blender:/app/blender
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data.db
      - SECRET_KEY=dev
    volumes:
      - ./backend:/app
      - ./public/models:/app/models
      - ./data:/app/data
